### ISSUE TITLE
ODK compliant

### ISSUE THREAD

**Issue by celineaubert** [AGROFIMS/hagrofims#252]

**Comment by omarbenites** [comment]
From Celine's email:
-----
I was pleased to see that the export to ODK is available in the last development version. Congratulation! I tried it and here is what I found:

The export worked properly for 2 over 3 fieldbook:

VRTO1610052425 – I was able to export the ODK form, but I did not manage to open it in ODK (I did not find why);
RIKS1608205712 – worked fine.
RRQX1609963864 – worked fine.
 
- [X] However, I noticed that once imported in ODK, all the AgroFIMS fieldbooks take the name ‘’AgroFIMS_group_looped’’ instead of their unique name. Therefore, it is difficult to recognize them in ODK. (Done ✔️ )

---

**Comment by omarbenites** [comment]
Now fixed and compatible with the latest ODK's version
